function FKRel = autogen_fwd_kin_rel(boardX,boardMass,boardTheta,boardHeight,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_FWD_KIN_REL
%    FKREL = AUTOGEN_FWD_KIN_REL(BOARDX,BOARDMASS,BOARDTHETA,BOARDHEIGHT,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-May-2020 14:22:08

t2 = sin(boardTheta);
t3 = boardX.*boardMass;
t4 = boardTheta+bottomLinkTheta;
t6 = boardMass+bottomLinkMass+topLinkMass;
t8 = -boardX;
t5 = sin(t4);
t7 = t4+topLinkTheta;
t10 = -t3;
t13 = (boardHeight.*t2)./2.0;
t15 = 1.0./t6;
t9 = sin(t7);
t11 = bottomLinkRCoM.*t5;
t12 = bottomLinkHeight.*t5;
t16 = -t13;
t14 = t9.*topLinkRCoM;
t17 = t8+t11+t13;
t18 = bottomLinkMass.*t17;
t19 = t8+t12+t13+t14;
t20 = t19.*topLinkMass;
t21 = t10+t18+t20;
t22 = t15.*t21;
FKRel = [boardX+t22,boardX-t11+t16+t22,boardX-t12-t14+t16+t22];
