function C_all = autogen_constraints(boardX,boardDTheta)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(BOARDX,BOARDDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-May-2020 09:32:27

t2 = cos(boardDTheta);
t3 = sin(boardDTheta);
t4 = t2./5.0;
t5 = t3./5.0;
t6 = t2.*3.15e-2;
t7 = t3.*3.15e-2;
C_all = [boardX-t4+t7+1.0./5.0;t5+t6;boardX+t4+t7-1.0./5.0;-t5+t6];
