function [bottomLinkDXCoM,bottomLinkDYCoM,topLinkDXCoM,topLinkDYCoM] = autogen_CoM_velocities(boardDX,boardDY,boardTheta,boardDTheta,bottomLinkRCoM,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,topLinkRCoM,topLinkTheta,topLinkDTheta)
%AUTOGEN_COM_VELOCITIES
%    [BOTTOMLINKDXCOM,BOTTOMLINKDYCOM,TOPLINKDXCOM,TOPLINKDYCOM] = AUTOGEN_COM_VELOCITIES(BOARDDX,BOARDDY,BOARDTHETA,BOARDDTHETA,BOTTOMLINKRCOM,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKTHETA,TOPLINKDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-May-2020 09:12:13

t2 = boardTheta+bottomLinkTheta;
t3 = cos(t2);
bottomLinkDXCoM = boardDX-boardDTheta.*bottomLinkRCoM.*t3-bottomLinkRCoM.*bottomLinkDTheta.*t3;
if nargout > 1
    t4 = sin(t2);
    bottomLinkDYCoM = boardDY-boardDTheta.*bottomLinkRCoM.*t4-bottomLinkRCoM.*bottomLinkDTheta.*t4;
end
if nargout > 2
    t5 = t2+topLinkTheta;
    t6 = sin(t5);
    t7 = cos(t5);
    t8 = bottomLinkHeight.*t3;
    t9 = bottomLinkHeight.*t4;
    t10 = t7.*topLinkRCoM;
    t11 = t6.*topLinkRCoM;
    t12 = t8+t10;
    topLinkDXCoM = boardDX-boardDTheta.*t12-bottomLinkDTheta.*t12-t10.*topLinkDTheta;
end
if nargout > 3
    t13 = t9+t11;
    topLinkDYCoM = boardDY-boardDTheta.*t13-bottomLinkDTheta.*t13-t11.*topLinkDTheta;
end
