function totEnergy = autogen_total_energy(boardI,boardY,boardDX,boardDY,boardMass,boardTheta,boardDTheta,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,g,topLinkI,topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta)
%AUTOGEN_TOTAL_ENERGY
%    TOTENERGY = AUTOGEN_TOTAL_ENERGY(BOARDI,BOARDY,BOARDDX,BOARDDY,BOARDMASS,BOARDTHETA,BOARDDTHETA,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,G,TOPLINKI,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPLINKDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-May-2020 23:17:52

t2 = boardTheta+bottomLinkTheta;
t6 = -boardDX;
t7 = -boardDY;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+topLinkTheta;
t8 = sin(t5);
t9 = cos(t5);
t10 = bottomLinkHeight.*t3;
t11 = bottomLinkHeight.*t4;
t12 = t9.*topLinkRCoM;
t13 = t8.*topLinkRCoM;
t14 = t10+t12;
t15 = t11+t13;
totEnergy = (topLinkMass.*((t6+boardDTheta.*t14+bottomLinkDTheta.*t14+t12.*topLinkDTheta).^2+(t7+boardDTheta.*t15+bottomLinkDTheta.*t15+t13.*topLinkDTheta).^2))./2.0+(bottomLinkI.*(boardDTheta+bottomLinkDTheta).^2)./2.0+(boardDX.^2.*boardMass)./2.0+(boardI.*boardDTheta.^2)./2.0+boardDY.^2+(topLinkI.*(boardDTheta+bottomLinkDTheta+topLinkDTheta).^2)./2.0+(bottomLinkMass.*((t6+boardDTheta.*bottomLinkRCoM.*t3+bottomLinkRCoM.*bottomLinkDTheta.*t3).^2+(t7+boardDTheta.*bottomLinkRCoM.*t4+bottomLinkRCoM.*bottomLinkDTheta.*t4).^2))./2.0+bottomLinkMass.*g.*(boardY+bottomLinkRCoM.*t3)+bottomLinkMass.*g.*(boardY+t14)+boardY.*boardMass.*g;
