function B = autogen_upright_input_matrix(boardMass,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkHeight,topLinkI,topLinkRCoM,topLinkMass)
%AUTOGEN_UPRIGHT_INPUT_MATRIX
%    B = AUTOGEN_UPRIGHT_INPUT_MATRIX(BOARDMASS,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKHEIGHT,TOPLINKI,TOPLINKRCOM,TOPLINKMASS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-May-2020 11:29:40

t2 = bottomLinkI.*topLinkI;
t3 = bottomLinkRCoM.^2;
t4 = bottomLinkHeight.^2;
t5 = topLinkRCoM.^2;
t6 = bottomLinkRCoM.*bottomLinkMass.*bottomLinkHeight;
t9 = bottomLinkRCoM.*bottomLinkMass.*topLinkI;
t10 = bottomLinkRCoM.*bottomLinkMass.*topLinkRCoM;
t12 = bottomLinkHeight.*topLinkI.*topLinkMass;
t13 = topLinkI.*topLinkRCoM.*topLinkMass;
t7 = boardMass.*t2;
t8 = bottomLinkMass.*t2;
t11 = t2.*topLinkMass;
t14 = bottomLinkMass.*t3;
t15 = bottomLinkI.*t5.*topLinkMass;
t16 = t4.*topLinkI.*topLinkMass;
t17 = t5.*topLinkI.*topLinkMass;
t18 = t12.*topLinkRCoM.*2.0;
t19 = -t6;
t20 = -t10;
t27 = bottomLinkRCoM.*bottomLinkMass.*t5.*topLinkMass;
t29 = t6.*topLinkI.*topLinkMass.*2.0;
t33 = t9.*topLinkRCoM.*topLinkMass.*2.0;
t21 = t14.*topLinkI;
t23 = boardMass.*t15;
t24 = boardMass.*t16;
t25 = bottomLinkMass.*t15;
t28 = bottomLinkMass.*t16;
t30 = boardMass.*t17;
t31 = bottomLinkMass.*t17;
t32 = boardMass.*t18;
t34 = bottomLinkMass.*t18;
t35 = -t29;
t36 = -t33;
t37 = t5.*t14.*topLinkMass;
t39 = bottomLinkI+t14+t19+t20;
t40 = t9+t12+t13+t27;
t22 = boardMass.*t21;
t26 = t21.*topLinkMass;
t38 = boardMass.*t37;
t41 = t2+t15+t16+t17+t18+t21+t37;
t42 = t7+t8+t11+t22+t23+t24+t25+t26+t28+t30+t31+t32+t34+t35+t36+t38;
t43 = 1.0./t42;
t44 = t40.*t43;
t45 = t39.*t43.*topLinkRCoM.*topLinkMass;
t46 = t41.*t43;
B = reshape([0.0,0.0,0.0,t46,t44,t45,0.0,0.0,0.0,t46,t44,t45],[6,2]);
