function constraints = autogen_constraints(boardY,boardTheta,boardHeight,boardLength)
%AUTOGEN_CONSTRAINTS
%    CONSTRAINTS = AUTOGEN_CONSTRAINTS(BOARDY,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-May-2020 23:17:51

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = -boardY;
t5 = (boardHeight.*t2)./2.0;
t6 = (boardLength.*t3)./2.0;
constraints = [t4+t5+t6;t4+t5-t6];
