function C = autogen_coriolis_matrix(bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta)
%AUTOGEN_CORIOLIS_MATRIX
%    C = AUTOGEN_CORIOLIS_MATRIX(BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPLINKDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-May-2020 11:29:23

t2 = sin(bottomLinkTheta);
t3 = sin(topLinkTheta);
t4 = bottomLinkTheta+topLinkTheta;
t5 = bottomLinkTheta.*2.0;
t6 = topLinkTheta.*2.0;
t7 = topLinkRCoM.^2;
t8 = sin(t5);
t9 = sin(t4);
t10 = bottomLinkTheta+t4;
t12 = bottomLinkHeight.*t3.*topLinkRCoM.*topLinkMass.*topLinkDTheta;
t13 = bottomLinkDTheta.*bottomLinkHeight.*t3.*topLinkRCoM.*topLinkMass;
t14 = t4.*2.0;
t11 = sin(t10);
t15 = t9.*topLinkRCoM.*topLinkMass.*topLinkDTheta;
t16 = sin(t14);
t17 = t9.*topLinkRCoM.*topLinkDTheta.*2.0;
t18 = -t12;
t19 = bottomLinkDTheta.*bottomLinkHeight.*t11.*topLinkRCoM.*topLinkMass;
t20 = bottomLinkHeight.*t11.*topLinkRCoM.*topLinkMass.*topLinkDTheta;
t23 = bottomLinkDTheta.*t7.*t16.*topLinkMass;
t24 = t7.*t16.*topLinkMass.*topLinkDTheta;
t21 = -t19;
t22 = -t20;
t25 = -t23;
t26 = -t24;
C = reshape([0.0,0.0,0.0,t15+(topLinkMass.*(t17+bottomLinkDTheta.*(bottomLinkHeight.*t2+t9.*topLinkRCoM).*2.0))./2.0+bottomLinkDTheta.*((topLinkMass.*(bottomLinkHeight.*t2.*2.0+t9.*topLinkRCoM.*2.0))./2.0+bottomLinkRCoM.*bottomLinkMass.*t2)+bottomLinkRCoM.*bottomLinkMass.*bottomLinkDTheta.*t2,t18-t19.*2.0+t22+t25+t26-bottomLinkRCoM.^2.*bottomLinkMass.*bottomLinkDTheta.*t8-bottomLinkDTheta.*bottomLinkHeight.^2.*t8.*topLinkMass,t13+t21+t25+t26,t15+(topLinkMass.*(t17+bottomLinkDTheta.*t9.*topLinkRCoM.*2.0))./2.0+bottomLinkDTheta.*t9.*topLinkRCoM.*topLinkMass,-t13+t18+t21+t22+t25+t26,t25+t26],[3,3]);
