function theta_m_eq = autogen_equilibrium_motor_angle(boardHeight,bottomLinkHeight,boarMass,bottomLinkMass,topLinkMass,wheelRadius,boardTheta,bottomLinkTheta,topLinkTheta,boardLength)
%AUTOGEN_EQUILIBRIUM_MOTOR_ANGLE
%    THETA_M_EQ = AUTOGEN_EQUILIBRIUM_MOTOR_ANGLE(BOARDMASS,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,BOTTOMLINKMASS,BOTTOMLINKTHETA,R,TOPLINKMASS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-May-2020 14:22:08

t2 = boardMass+bottomLinkMass+topLinkMass;
theta_m_eq = -((boardHeight.*bottomLinkMass)./2.0-(t2.*((boardLength.*cos(boardTheta))./2.0-(boardHeight.*sin(boardTheta).*(bottomLinkMass+t2+topLinkMass))./(t2.*2.0)))./sin(boardTheta+bottomLinkTheta))./(boardMass.*wheelRadius);
