function A = autogen_upright_state_matrix(boardMass,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkHeight,g,topLinkI,topLinkRCoM,topLinkMass)
%AUTOGEN_UPRIGHT_STATE_MATRIX
%    A = AUTOGEN_UPRIGHT_STATE_MATRIX(BOARDMASS,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKHEIGHT,G,TOPLINKI,TOPLINKRCOM,TOPLINKMASS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-May-2020 11:29:39

t2 = boardMass.*bottomLinkI;
t3 = bottomLinkI.*bottomLinkMass;
t4 = bottomLinkI.*topLinkMass;
t5 = bottomLinkRCoM.^2;
t6 = bottomLinkHeight.^2;
t7 = topLinkRCoM.^2;
t10 = bottomLinkRCoM.*bottomLinkMass.*topLinkI;
t12 = bottomLinkHeight.*topLinkI.*topLinkMass;
t13 = topLinkI.*topLinkRCoM.*topLinkMass;
t14 = boardMass.*bottomLinkHeight.*topLinkRCoM.*topLinkMass;
t15 = bottomLinkRCoM.*bottomLinkMass.*topLinkRCoM.*topLinkMass;
t16 = bottomLinkMass.*bottomLinkHeight.*topLinkRCoM.*topLinkMass;
t18 = bottomLinkRCoM.*bottomLinkMass.*bottomLinkHeight.*topLinkMass.*2.0;
t8 = t2.*topLinkI;
t9 = t3.*topLinkI;
t11 = t4.*topLinkI;
t17 = boardMass.*bottomLinkMass.*t5;
t20 = t2.*t7.*topLinkMass;
t21 = boardMass.*t6.*topLinkI.*topLinkMass;
t22 = t3.*t7.*topLinkMass;
t23 = bottomLinkMass.*t5.*topLinkI.*topLinkMass;
t24 = bottomLinkMass.*t6.*topLinkI.*topLinkMass;
t25 = bottomLinkHeight.*t10.*topLinkMass.*2.0;
t26 = boardMass.*t7.*topLinkI.*topLinkMass;
t27 = bottomLinkMass.*t7.*topLinkI.*topLinkMass;
t28 = boardMass.*t12.*topLinkRCoM.*2.0;
t29 = t10.*topLinkRCoM.*topLinkMass.*2.0;
t30 = bottomLinkMass.*t12.*topLinkRCoM.*2.0;
t31 = -t18;
t19 = t17.*topLinkI;
t32 = -t25;
t33 = -t29;
t34 = t7.*t17.*topLinkMass;
t35 = t8+t9+t11+t19+t20+t21+t22+t23+t24+t26+t27+t28+t30+t32+t33+t34;
t36 = 1.0./t35;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,bottomLinkMass.*g.*t36.*(bottomLinkRCoM.*t12+bottomLinkRCoM.*t13+bottomLinkHeight.*t10+t4.*t7+t10.*topLinkRCoM+t12.*topLinkRCoM.*2.0+bottomLinkMass.*t5.*topLinkI+t6.*topLinkI.*topLinkMass+t7.*topLinkI.*topLinkMass+bottomLinkMass.*t5.*t7.*topLinkMass.*2.0),bottomLinkMass.*g.*t36.*(t10+t12+t13+boardMass.*bottomLinkRCoM.*topLinkI+boardMass.*bottomLinkHeight.*topLinkI+bottomLinkMass.*bottomLinkHeight.*topLinkI+boardMass.*topLinkI.*topLinkRCoM+bottomLinkRCoM.*topLinkI.*topLinkMass+bottomLinkMass.*topLinkI.*topLinkRCoM+boardMass.*bottomLinkRCoM.*t7.*topLinkMass+bottomLinkRCoM.*bottomLinkMass.*t7.*topLinkMass.*2.0),bottomLinkMass.*g.*t36.*topLinkRCoM.*(t2+t3+t4-t15.*2.0+t17+t31+bottomLinkMass.*t5.*topLinkMass.*2.0-boardMass.*bottomLinkRCoM.*topLinkRCoM.*topLinkMass-boardMass.*bottomLinkRCoM.*bottomLinkHeight.*topLinkMass),0.0,0.0,0.0,bottomLinkMass.*g.*t36.*topLinkRCoM.*(t10+t12+t13-bottomLinkHeight.*t15+t4.*topLinkRCoM+bottomLinkMass.*t5.*topLinkRCoM.*topLinkMass),bottomLinkMass.*g.*t36.*topLinkRCoM.*(-t14+t15-t16+boardMass.*topLinkI+bottomLinkMass.*topLinkI+topLinkI.*topLinkMass),bottomLinkMass.*g.*t36.*topLinkRCoM.*(t2+t3+t4+t14-t15+t16+t17+t31+boardMass.*t6.*topLinkMass+bottomLinkMass.*t5.*topLinkMass+bottomLinkMass.*t6.*topLinkMass),1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
