function g_ss = autogen_control_vector_field(I_pend,m_cart,m_pend,r_com_pend,theta_pend)
%AUTOGEN_CONTROL_VECTOR_FIELD
%    G_SS = AUTOGEN_CONTROL_VECTOR_FIELD(I_PEND,M_CART,M_PEND,R_COM_PEND,THETA_PEND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Apr-2020 15:27:27

t2 = sin(theta_pend);
t3 = I_pend.*m_cart;
t4 = I_pend.*m_pend;
t5 = m_pend.^2;
t6 = r_com_pend.^2;
t7 = t2.^2;
t8 = m_cart.*m_pend.*t6;
t9 = t5.*t6;
t10 = t7.*t9;
t11 = -t10;
t12 = t3+t4+t8+t9+t11;
t13 = 1.0./t12;
g_ss = [0.0;0.0;t13.*(I_pend+m_pend.*t6);m_pend.*r_com_pend.*t2.*t13];
