function FK = autogen_fwd_kin(boardX,boardY,boardTheta,bottomLinkRCoM,bottomLinkTheta,bottomLinkHeight,topLinkRCoM,topLinkTheta,topLinkHeight)
%AUTOGEN_FWD_KIN
%    FK = AUTOGEN_FWD_KIN(BOARDX,BOARDY,BOARDTHETA,BOTTOMLINKRCOM,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKTHETA,TOPLINKHEIGHT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2020 18:43:24

t2 = boardTheta+bottomLinkTheta;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+topLinkTheta;
t6 = sin(t5);
t7 = cos(t5);
t8 = bottomLinkHeight.*t3;
t9 = bottomLinkHeight.*t4;
t10 = -t9;
FK = reshape([boardX,boardY,boardX-bottomLinkRCoM.*t4,boardY+bottomLinkRCoM.*t3,boardX+t10-t6.*topLinkRCoM,boardY+t8+t7.*topLinkRCoM,boardX+t10-t6.*topLinkHeight,boardY+t8+t7.*topLinkHeight],[2,4]);
