function H = autogen_H_eom(boardMass,boardTheta,boardDTheta,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,g,topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta)
%AUTOGEN_H_EOM
%    H = AUTOGEN_H_EOM(BOARDMASS,BOARDTHETA,BOARDDTHETA,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,G,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPLINKDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-May-2020 09:16:43

t2 = sin(topLinkTheta);
t3 = boardTheta+bottomLinkTheta;
t4 = boardDTheta.^2;
t5 = bottomLinkDTheta.^2;
t6 = topLinkDTheta.^2;
t7 = cos(t3);
t8 = sin(t3);
t9 = t3+topLinkTheta;
t14 = bottomLinkHeight.*t2.*t6.*topLinkRCoM.*topLinkMass;
t15 = boardDTheta.*bottomLinkHeight.*t2.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0;
t16 = bottomLinkDTheta.*bottomLinkHeight.*t2.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0;
t10 = sin(t9);
t11 = cos(t9);
t12 = bottomLinkRCoM.*bottomLinkMass.*g.*t8;
t13 = bottomLinkMass.*bottomLinkHeight.*g.*t8;
t20 = -t15;
t21 = -t16;
t22 = -t14;
t17 = bottomLinkMass.*g.*t10.*topLinkRCoM;
t18 = -t12;
t19 = -t13;
t23 = -t17;
t24 = t18+t19+t20+t21+t22+t23;
H = [bottomLinkRCoM.*bottomLinkMass.*t4.*t8+bottomLinkRCoM.*bottomLinkMass.*t5.*t8+bottomLinkHeight.*t4.*t8.*topLinkMass+bottomLinkHeight.*t5.*t8.*topLinkMass+t4.*t10.*topLinkRCoM.*topLinkMass+t5.*t10.*topLinkRCoM.*topLinkMass+t6.*t10.*topLinkRCoM.*topLinkMass+boardDTheta.*bottomLinkRCoM.*bottomLinkMass.*bottomLinkDTheta.*t8.*2.0+boardDTheta.*bottomLinkDTheta.*bottomLinkHeight.*t8.*topLinkMass.*2.0+boardDTheta.*bottomLinkDTheta.*t10.*topLinkRCoM.*topLinkMass.*2.0+boardDTheta.*t10.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0+bottomLinkDTheta.*t10.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0;boardMass.*g+bottomLinkMass.*g.*2.0-bottomLinkRCoM.*bottomLinkMass.*t4.*t7-bottomLinkRCoM.*bottomLinkMass.*t5.*t7-bottomLinkHeight.*t4.*t7.*topLinkMass-bottomLinkHeight.*t5.*t7.*topLinkMass-t4.*t11.*topLinkRCoM.*topLinkMass-t5.*t11.*topLinkRCoM.*topLinkMass-t6.*t11.*topLinkRCoM.*topLinkMass-boardDTheta.*bottomLinkRCoM.*bottomLinkMass.*bottomLinkDTheta.*t7.*2.0-boardDTheta.*bottomLinkDTheta.*bottomLinkHeight.*t7.*topLinkMass.*2.0-boardDTheta.*bottomLinkDTheta.*t11.*topLinkRCoM.*topLinkMass.*2.0-boardDTheta.*t11.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0-bottomLinkDTheta.*t11.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*2.0;t24;t24;topLinkRCoM.*(-bottomLinkMass.*g.*t10+bottomLinkHeight.*t2.*t4.*topLinkMass+bottomLinkHeight.*t2.*t5.*topLinkMass+boardDTheta.*bottomLinkDTheta.*bottomLinkHeight.*t2.*topLinkMass.*2.0)];
