function totEnergy = autogen_total_energy(boardI,boardY,boardDX,boardDY,boardMass,boardTheta,boardDTheta,boardHeight,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,g,topLinkI,topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta,wheelRadius)
%AUTOGEN_TOTAL_ENERGY
%    TOTENERGY = AUTOGEN_TOTAL_ENERGY(BOARDI,BOARDY,BOARDDX,BOARDDY,BOARDMASS,BOARDTHETA,BOARDDTHETA,BOARDHEIGHT,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,G,TOPLINKI,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPLINKDTHETA,WHEELRADIUS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-May-2020 14:56:07

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = boardTheta+bottomLinkTheta;
t8 = -boardDX;
t9 = -boardDY;
t11 = boardHeight./2.0;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+topLinkTheta;
t16 = t2.*t11;
t17 = t3.*t11;
t10 = sin(t7);
t12 = cos(t7);
t13 = bottomLinkRCoM.*t5;
t14 = bottomLinkHeight.*t5;
t15 = bottomLinkHeight.*t6;
t18 = t12.*topLinkRCoM;
t19 = t10.*topLinkRCoM;
totEnergy = (bottomLinkMass.*((t8+boardDTheta.*(t13+t16)+bottomLinkDTheta.*t13).^2+(t9+boardDTheta.*(t17+bottomLinkRCoM.*t6)+bottomLinkRCoM.*bottomLinkDTheta.*t6).^2))./2.0+(topLinkMass.*((t8+bottomLinkDTheta.*(t14+t18)+t18.*topLinkDTheta+boardDTheta.*(t14+t16+t18)).^2+(t9+bottomLinkDTheta.*(t15+t19)+t19.*topLinkDTheta+boardDTheta.*(t15+t17+t19)).^2))./2.0+(bottomLinkI.*(boardDTheta+bottomLinkDTheta).^2)./2.0+(boardI.*boardDTheta.^2)./2.0+(boardMass.*(boardDX.^2+boardDY.^2))./2.0+g.*(bottomLinkMass.*(boardY+t11+t13+t16+wheelRadius)+boardMass.*(boardY+t11+wheelRadius)+topLinkMass.*(boardY+t11+t14+t16+t18+wheelRadius))+(topLinkI.*(boardDTheta+bottomLinkDTheta+topLinkDTheta).^2)./2.0;
