function G = autogen_grav_vector(boardMass,boardTheta,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,g,topLinkRCoM,topLinkTheta)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(BOARDMASS,BOARDTHETA,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,G,TOPLINKRCOM,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
<<<<<<< HEAD
%    01-May-2020 09:52:33
=======
%    30-Apr-2020 22:22:14
>>>>>>> 57d8f43bd5fa33b53ad544a97974782202f2f5fc

t2 = boardTheta+bottomLinkTheta;
t3 = sin(t2);
t4 = t2+topLinkTheta;
t5 = sin(t4);
t6 = bottomLinkRCoM.*bottomLinkMass.*t3;
t7 = bottomLinkMass.*bottomLinkHeight.*t3;
t8 = bottomLinkMass.*t5.*topLinkRCoM;
t9 = t6+t7+t8;
t10 = g.*t9;
t11 = -t10;
G = [0.0;g.*(boardMass+bottomLinkMass.*2.0);t11;t11;-g.*t8];
