function [dFK_com_s,dFK_com_b] = autogen_jacobians(l_f,l_s,p_b,r,theta_f,theta_m,theta_s,theta_dot_f,theta_dot_m,theta_dot_s,x_dot_f,z_dot_f)
%AUTOGEN_JACOBIANS
%    [DFK_COM_S,DFK_COM_B] = AUTOGEN_JACOBIANS(L_F,L_S,P_B,R,THETA_F,THETA_M,THETA_S,THETA_DOT_F,THETA_DOT_M,THETA_DOT_S,X_DOT_F,Z_DOT_F)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-May-2020 09:37:42

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = theta_f+theta_s;
t5 = l_f.*t2;
t6 = cos(t4);
t7 = l_f.*t3;
t8 = sin(t4);
dFK_com_s = [x_dot_f-theta_dot_f.*(t5+l_s.*t6)-l_s.*t6.*theta_dot_s;z_dot_f-theta_dot_f.*(t7+l_s.*t8)-l_s.*t8.*theta_dot_s];
if nargout > 1
    t9 = p_b.*t6;
    t10 = p_b.*t8;
    t11 = r.*t8.*theta_m;
    t12 = r.*t6.*theta_m;
    dFK_com_b = [x_dot_f+theta_dot_s.*(t10-t12)-theta_dot_f.*(t5-t10+t12)-r.*t8.*theta_dot_m;z_dot_f-theta_dot_s.*(t9+t11)-theta_dot_f.*(t7+t9+t11)+r.*t6.*theta_dot_m];
end
