function constraints_ramp_lip = autogen_constraints_ramp_lip(boardY,boardTheta,boardHeight,boardLength,wheelRadius)
%AUTOGEN_CONSTRAINTS_RAMP_LIP
%    CONSTRAINTS_RAMP_LIP = AUTOGEN_CONSTRAINTS_RAMP_LIP(BOARDY,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,WHEELRADIUS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Jun-2020 17:56:51

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t5 = -boardY;
t6 = -wheelRadius;
t7 = boardHeight./2.0;
t4 = t2.*wheelRadius;
t8 = -t7;
t9 = t2.*t7;
t10 = (boardLength.*t3)./2.0;
constraints_ramp_lip = [t4+t5+t6+t8+t9+t10+2.0;t4+t5+t6+t8+t9-t10+2.0];
