function M = autogen_mass_matrix(boardI,boardMass,boardTheta,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,topLinkI,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(BOARDI,BOARDMASS,BOARDTHETA,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKI,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-May-2020 23:18:07

t2 = cos(topLinkTheta);
t3 = boardTheta+bottomLinkTheta;
t4 = bottomLinkRCoM.^2;
t5 = bottomLinkHeight.^2;
t6 = topLinkRCoM.^2;
t7 = cos(t3);
t8 = sin(t3);
t9 = t3+topLinkTheta;
t11 = bottomLinkMass.*t4;
t12 = t5.*topLinkMass;
t13 = t6.*topLinkMass;
t15 = bottomLinkHeight.*t2.*topLinkRCoM.*topLinkMass;
t10 = sin(t9);
t14 = cos(t9);
t16 = bottomLinkHeight.*t7.*2.0;
t17 = bottomLinkHeight.*t8.*2.0;
t18 = t15.*2.0;
t19 = bottomLinkRCoM.*bottomLinkMass.*t7;
t20 = bottomLinkRCoM.*bottomLinkMass.*t8;
t29 = t13+t15+topLinkI;
t21 = t14.*topLinkRCoM.*topLinkMass;
t22 = t10.*topLinkRCoM.*topLinkMass;
t23 = t14.*topLinkRCoM.*2.0;
t24 = t10.*topLinkRCoM.*2.0;
t25 = -t19;
t26 = -t20;
t36 = bottomLinkI+t11+t12+t13+t18+topLinkI;
t27 = -t21;
t28 = -t22;
t30 = t16+t23;
t31 = t17+t24;
t32 = (t30.*topLinkMass)./2.0;
t33 = (t31.*topLinkMass)./2.0;
t34 = -t32;
t35 = -t33;
t37 = t25+t34;
t38 = t26+t35;
M = reshape([boardMass+bottomLinkMass+topLinkMass,0.0,t37,t37,t27,0.0,bottomLinkMass+topLinkMass+2.0,t38,t38,t28,t37,t38,boardI+t36,t36,t29,t37,t38,t36,t36,t29,t27,t28,t29,t29,t13+topLinkI],[5,5]);
