function M = autogen_mass_matrix(boardMass,bottomLinkI,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,topLinkI,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(BOARDMASS,BOTTOMLINKI,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKI,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-May-2020 11:29:22

t2 = cos(bottomLinkTheta);
t3 = cos(topLinkTheta);
t4 = bottomLinkTheta+topLinkTheta;
t5 = bottomLinkTheta.*2.0;
t6 = bottomLinkRCoM.^2;
t7 = bottomLinkHeight.^2;
t8 = topLinkTheta.*2.0;
t9 = topLinkRCoM.^2;
t10 = cos(t5);
t11 = bottomLinkHeight.*t3;
t12 = cos(t4);
t13 = bottomLinkTheta+t4;
t14 = bottomLinkRCoM.*bottomLinkMass.*t2;
t18 = t4.*2.0;
t20 = (t9.*topLinkMass)./2.0;
t15 = cos(t13);
t16 = t12.*topLinkRCoM.*topLinkMass;
t17 = -t14;
t19 = cos(t18);
t21 = bottomLinkHeight.*t15;
t22 = -t16;
t23 = t19.*topLinkRCoM;
t24 = t19.*t20;
t25 = t11+t21+t23+topLinkRCoM;
t26 = (t25.*topLinkRCoM.*topLinkMass)./2.0;
M = reshape([boardMass+bottomLinkMass+topLinkMass,t17+t22-bottomLinkHeight.*t2.*topLinkMass,t22,t17-(topLinkMass.*(bottomLinkHeight.*t2.*2.0+t12.*topLinkRCoM.*2.0))./2.0,bottomLinkI+t20+t24+(bottomLinkMass.*t6)./2.0+(t7.*topLinkMass)./2.0+(bottomLinkMass.*t6.*t10)./2.0+(t7.*t10.*topLinkMass)./2.0+t11.*topLinkRCoM.*topLinkMass+t21.*topLinkRCoM.*topLinkMass,t26,t22,t26,t20+t24+topLinkI],[3,3]);
