function [A_all,H_constL,H_constR] = autogen_constraint_derivatives(boardTheta,boardHeight,boardLength,wheelRadius)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_ALL,H_CONSTL,H_CONSTR] = AUTOGEN_CONSTRAINT_DERIVATIVES(BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,WHEELRADIUS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-May-2020 19:31:22

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = t2.*wheelRadius;
t5 = t3.*wheelRadius;
t8 = (boardHeight.*t2)./2.0;
t9 = (boardLength.*t2)./2.0;
t10 = (boardHeight.*t3)./2.0;
t11 = (boardLength.*t3)./2.0;
t6 = -t4;
t7 = -t5;
t12 = -t8;
t13 = -t10;
A_all = reshape([0.0,0.0,-1.0,-1.0,t7+t9+t13,t7-t9+t13,0.0,0.0,0.0,0.0],[2,5]);
if nargout > 1
    H_constL = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6-t11+t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 2
    H_constR = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6+t11+t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
