function [FK_leftWheel,FK_rightWheel] = autogen_fk_wheels(boardX,boardY,boardTheta,boardHeight,boardLength,wheelRadius)
%AUTOGEN_FK_WHEELS
%    [FK_LEFTWHEEL,FK_RIGHTWHEEL] = AUTOGEN_FK_WHEELS(BOARDX,BOARDY,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,WHEELRADIUS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-May-2020 17:14:37

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t6 = boardHeight./2.0;
t4 = t2.*wheelRadius;
t5 = t3.*wheelRadius;
t8 = t2.*t6;
t9 = (boardLength.*t2)./2.0;
t10 = t3.*t6;
t11 = (boardLength.*t3)./2.0;
t12 = boardHeight.*t2.*(-1.0./2.0);
t7 = -t4;
FK_leftWheel = [boardX+t5-t9+t10;boardY+t6+t7-t11+t12+wheelRadius];
if nargout > 1
    FK_rightWheel = [boardX+t5+t9+t10;boardY+t6+t7+t11+t12+wheelRadius];
end
