%% equilibrium_motor_angle.m
%
% Description:
%   Wrapper function for autogen_equilibrium_motor_angle.m
%   Computes the body motor rotation needed to put the robot in an
%   equilibrium configuration, given boardTheta, bottomLinkTheta, and
%   topLinkTheta
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   theta_m_eq = values of motor angle that establishes equilibrium

function [theta_m_eq] = equilibrium_motor_angle(x,params)

boardTheta = x(1);
bottomLinkTheta = x(2);
topLinkTheta = x(3);

boardHeight = params.boardHeight/2;
bottomLinkHeight =  params.bottomLinkHeight;
boardMass = params.boardMass;
bottomLinkMass = params.bottomLinkMass;
topLinkMass = params.topLinkMass;
wheelRadius = params.wheelRadius;
boardLength = params.boardLength/2;

theta_m_eq = autogen_equilibrium_motor_angle(boardHeight,bottomLinkHeight,boardMass,bottomLinkMass,topLinkMass,wheelRadius,boardTheta,bottomLinkTheta,topLinkTheta,boardLength);
end