%% fwk_kin.m
%
% Description:
%   Wrapper function for autogen_fwd_kin.m
%   Computes the forward kinematics for three points on the robot.
%
% Inputs:
%   q: robot configuration, q = [x_cart; theta_pend];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   FK: a 2x3 matrix of (x,y) locations of three points on the robot. Row 1
%   is the x-coordinate, row 2 is the y-coordinate:
%       FK = [x_cart, x_pend_com, x_pend_tip;
%             0,      y_pend_com, y_pend_tip];

function [FK] = fwd_kin(q,params)
    boardX = q(1);
    boardY = 0;
    boardTheta = 0;
    bottomLinkTheta = q(2);
    topLinkTheta = q(3);
% boardX,boardY,boardMass,boardTheta,bottomLinkRCoM,
% bottomLinkMass,bottomLinkTheta,bottomLinkHeight,
% topLinkRCoM,topLinkMass,topLinkTheta,topLinkHeight

    FK = autogen_fwd_kin(boardX,... 
                         boardY,... 
                         params.boardMass,...
                         boardTheta, ...
                         params.bottomLinkYCoM, ...
                         params.bottomLinkMass,...
                         bottomLinkTheta, ...
                         params.bottomLinkHeight,...
                         params.topLinkYCoM,...
                         params.topLinkMass,...
                         topLinkTheta,...
                         params.topLinkHeight);
end