%% upright_state_matrix.m
%
% Description:
%   Wrapper function for autogen_upright_state_matrix.m
%   Computes the state matrix for linearized cart-pendulum dynamics in the
%   neighborhood of the upright (unstable) equilibrium.
%
% Inputs:
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs
%   A: 4x4 state matrix

function A = upright_state_matrix(params)

% boardI,boardMass,bottomLinkI,bottomLinkRCoM,
% bottomLinkMass,bottomLinkHeight,g,
% topLinkI,topLinkRCoM,topLinkMass

    A = autogen_upright_state_matrix(params.boardI,...
                                     params.boardMass,...
                                     params.bottomLinkI,...
                                     params.bottomLinkYCoM,...
                                     params.params.bottomLinkMass,...
                                     params.bottomLinkHeight,...
                                     params.g,...
                                     params.topLinkI,...
                                     params.topLinkYCoM,...
                                     params.topLinkMass);

end