%% upright_state_matrix.m
%
% Description:
%   Wrapper function for autogen_upright_state_matrix.m
%   Computes the state matrix for linearized cart-pendulum dynamics in the
%   neighborhood of the upright (unstable) equilibrium.
%
% Inputs:
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs
%   A: 4x4 state matrix

function A = upright_state_matrix(params)

    A = autogen_upright_state_matrix(params.model.dyn.pend.I,...
                                     params.model.dyn.b1,...
                                     params.model.dyn.b2,...
                                     params.model.dyn.g,...
                                     params.model.dyn.cart.m,...
                                     params.model.dyn.pend.m,...
                                     params.model.dyn.pend.r_com);

end