%% wheel_velocities.m
%
% Description:
%   Wrapper function for autogen_foot_velocities.m
%   Computes the velocities of the left and right feet of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot; s];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   leftWheelVelo, rightWheelVelo = wheel velocities

function [leftWheelVelo,rightWheelVelo] = wheel_velocities(x,params)

% autogen inputs: 
% boardDX,boardDY,boardTheta,boardDTheta,boardHeight,boardLength,wheelRadius

[leftWheelVelo,rightWheelVelo] = autogen_wheel_velocities(x(6), x(7), x(3), x(8), ...
                                    params.boardHeight, params.boardLength,...
                                    params.wheelRadius);

end
