%% wheel_coordinates.m
%
% Description:
%   Wrapper function for autogen_fk_wheels.m
%   Computes the locations of the left and right feet of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot; s];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   r_l, r_r = wheel coordinates

function [r_l,r_r] = wheel_coordinates(x,params)

% boardX,boardY,boardTheta,boardHeight,boardLength,wheelRadius

[r_l,r_r] = autogen_fk_wheels(x(1), x(2), x(3), params.boardHeight,...
                            params.boardLength, params.wheelRadius);

end
