function C = autogen_coriolis_matrix(b1,b2,b3,b4,b5,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta)
%AUTOGEN_CORIOLIS_MATRIX
%    C = AUTOGEN_CORIOLIS_MATRIX(B1,B2,B3,B4,B5,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKDTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA,TOPLINKDTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2020 20:18:48

t2 = sin(bottomLinkTheta);
t3 = cos(topLinkTheta);
t4 = sin(topLinkTheta);
t5 = bottomLinkTheta.*2.0;
t6 = sin(t5);
C = reshape([b1,0.0,0.0,0.0,0.0,0.0,b2,0.0,0.0,0.0,0.0,0.0,b3,0.0,0.0,-bottomLinkDTheta.*(bottomLinkRCoM.*bottomLinkMass.*t2+bottomLinkHeight.*t2.*topLinkMass)-bottomLinkDTheta.*bottomLinkHeight.*t2.*topLinkMass-bottomLinkRCoM.*bottomLinkMass.*bottomLinkDTheta.*t2,0.0,0.0,b4-bottomLinkRCoM.^2.*bottomLinkMass.*bottomLinkDTheta.*t6-bottomLinkDTheta.*bottomLinkHeight.^2.*t6.*topLinkMass,bottomLinkDTheta.*bottomLinkHeight.*t2.*t3.*topLinkRCoM.*topLinkMass.*-2.0,t4.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*-2.0,0.0,0.0,bottomLinkHeight.*t4.*topLinkRCoM.*topLinkMass.*topLinkDTheta.*cos(bottomLinkTheta).*-2.0,b5-t3.*t4.*topLinkRCoM.^2.*topLinkMass.*topLinkDTheta.*2.0],[5,5]);
