function FK = autogen_fwd_kin(boardX,boardY,bottomLinkRCoM,bottomLinkTheta,bottomLinkHeight,topLinkRCoM,topLinkTheta,topLinkHeight)
%AUTOGEN_FWD_KIN
%    FK = AUTOGEN_FWD_KIN(BOARDX,BOARDY,BOTTOMLINKRCOM,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKTHETA,TOPLINKHEIGHT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2020 20:18:44

t2 = cos(bottomLinkTheta);
t3 = sin(bottomLinkTheta);
t4 = cos(topLinkTheta);
t5 = sin(topLinkTheta);
t6 = bottomLinkHeight.*t2;
t7 = bottomLinkHeight.*t3;
FK = reshape([boardX,boardY,boardX+bottomLinkRCoM.*t3,boardY+bottomLinkRCoM.*t2,boardX+t7+t5.*topLinkRCoM,boardY+t6+t4.*topLinkRCoM,boardX+t7+t5.*topLinkHeight,boardY+t6+t4.*topLinkHeight],[2,4]);
