function M = autogen_mass_matrix(boardMass,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,topLinkRCoM,topLinkMass,topLinkTheta)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(BOARDMASS,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKRCOM,TOPLINKMASS,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2020 20:18:47

t2 = cos(bottomLinkTheta);
t3 = cos(topLinkTheta);
t4 = bottomLinkRCoM.*bottomLinkMass;
t5 = bottomLinkHeight.*topLinkMass;
t6 = t3.*topLinkRCoM.*topLinkMass;
t7 = t4+t5;
t8 = t2.*t3.*t5.*topLinkRCoM;
t9 = t2.*t7;
M = reshape([boardMass+bottomLinkMass+topLinkMass,0.0,0.0,t9,t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t9,0.0,0.0,t2.^2.*(bottomLinkRCoM.*t4+bottomLinkHeight.*t5),t8,t6,0.0,0.0,t8,t3.*t6.*topLinkRCoM],[5,5]);
