function G = autogen_grav_vector(boardMass,bottomLinkRCoM,bottomLinkMass,bottomLinkTheta,bottomLinkHeight,g,topLinkRCoM,topLinkTheta)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(BOARDMASS,BOTTOMLINKRCOM,BOTTOMLINKMASS,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,G,TOPLINKRCOM,TOPLINKTHETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2020 20:18:48

t2 = sin(bottomLinkTheta);
G = [0.0;g.*(boardMass+bottomLinkMass.*2.0);0.0;-g.*(bottomLinkRCoM.*bottomLinkMass.*t2+bottomLinkMass.*bottomLinkHeight.*t2);-bottomLinkMass.*g.*topLinkRCoM.*sin(topLinkTheta)];
