%% control_vector_field.m
%
% Description:
%   Wrapper function for autogen_control_vector_field.m
%   Computes the control vector field for the nonlinear state-space
%   dynamics of the cart-pendulum robot.
%
% Inputs:
%   x: the state vector, x = [x_cart; theta_pend; dx_cart; dtheta_pend];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   g_ss: a 4x1 vector that maps control input u to dx (time derivative of
%       the state x).

function g_ss = control_vector_field(x,params)

theta_pend = x(2);

g_ss = autogen_control_vector_field(params.model.dyn.pend.I,...
                                    params.model.dyn.cart.m,...
                                    params.model.dyn.pend.m,...
                                    params.model.dyn.pend.r_com,...
                                    theta_pend);

end