%% fwk_kin.m
%
% Description:
%   Wrapper function for autogen_fwd_kin.m
%   Computes the forward kinematics for three points on the robot.
%
% Inputs:
%   q: robot configuration, q = [x_cart; theta_pend];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   FK: a 2x3 matrix of (x,y) locations of three points on the robot. Row 1
%   is the x-coordinate, row 2 is the y-coordinate:
%       FK = [x_cart, x_pend_com, x_pend_tip;
%             0,      y_pend_com, y_pend_tip];

function [FK] = fwd_kin(q,params)
    x_cart = q(1);
    theta_pend = q(2);

    FK = autogen_fwd_kin(params.model.geom.pend.l,...
                         params.model.dyn.pend.r_com,...
                         theta_pend,x_cart);
end