%% upright_input_matrix.m
%
% Description:
%   Wrapper function for autogen_upright_input_matrix.m
%   Computes the input matrix for linearized cart-pendulum dynamics in the
%   neighborhood of the upright (unstable) equilibrium.
%
% Inputs:
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs
%   B: 4x1 input matrix

function B = upright_input_matrix(params)
    B = autogen_upright_input_matrix(params.model.dyn.pend.I,...
                                     params.model.dyn.cart.m,...
                                     params.model.dyn.pend.m,...
                                     params.model.dyn.pend.r_com);
end