function [KE,PE] = autogen_energy(J_b,J_f,J_m,J_s,K,g,h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,theta_dot_f,theta_dot_m,theta_dot_s,w_f)
%AUTOGEN_ENERGY
%    [KE,PE] = AUTOGEN_ENERGY(J_B,J_F,J_M,J_S,K,G,H_F,L_F,L_S,M_B,M_F,M_S,R,THETA_F,THETA_M,THETA_S,THETA_DOT_F,THETA_DOT_M,THETA_DOT_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-May-2020 20:00:10

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = l_s.*m_s;
t5 = m_b+m_s;
t6 = r.*theta_m;
t7 = theta_f+theta_s;
t8 = theta_dot_f+theta_dot_s;
t9 = theta_dot_f.^2;
t20 = -h_f;
t21 = -l_f;
t10 = h_f.*t2;
t11 = l_f.*t2;
t12 = m_f+t5;
t13 = cos(t7);
t14 = t2.*w_f;
t15 = h_f.*t3;
t16 = m_b.*t6;
t17 = l_f.*t3;
t18 = sin(t7);
t19 = t3.*w_f;
t22 = t8.^2;
t23 = -t14;
t24 = 1.0./t12;
t25 = t4+t16;
t26 = t5.*t24;
t28 = m_b.*r.*t18.*t24.*theta_dot_m;
t29 = t24.*t25;
t27 = t26-1.0;
t31 = -t29;
t30 = t11.*t27;
t32 = l_s+t31;
t34 = t6+t31;
KE = (J_b.*t22)./2.0+(J_f.*t9)./2.0+(J_s.*t22)./2.0+(m_s.*((theta_dot_f.*(t15+t17+t23+l_s.*t18)+l_s.*t18.*theta_dot_s).^2+(t28+theta_dot_f.*(t30-t13.*t32)-t13.*t32.*theta_dot_s).^2))./2.0+(J_m.*(t8+theta_dot_m).^2)./2.0+(m_b.*((theta_dot_f.*(t15+t17+t23+t6.*t18)-r.*t13.*theta_dot_m+t6.*t18.*theta_dot_s).^2+(-theta_dot_f.*(t30-t13.*t34)+t13.*t34.*theta_dot_s+t18.*theta_dot_m.*(r-m_b.*r.*t24)).^2))./2.0+(m_f.*((t28+theta_dot_f.*(t11.*t26+t13.*t29)+t13.*t29.*theta_dot_s).^2+t9.*(t14-t15).^2))./2.0;
if nargout > 1
    PE = (K.*theta_s.^2)./2.0+g.*m_b.*(t10+t11+t19+t20+t21+t6.*t13)+g.*m_s.*(-l_s+t10+t11+t19+t20+t21+l_s.*t13)+g.*m_f.*(t10+t19+t20);
end
