function [FK_pivot,FK_tip] = autogen_fk_viz(boardX,boardY,boardTheta,boardHeight,boardLength,bottomLinkTheta,bottomLinkHeight,topLinkTheta,topLinkHeight,wheelRadius)
%AUTOGEN_FK_VIZ
%    [FK_PIVOT,FK_TIP] = AUTOGEN_FK_VIZ(BOARDX,BOARDY,BOARDTHETA,BOARDHEIGHT,BOARDLENGTH,BOTTOMLINKTHETA,BOTTOMLINKHEIGHT,TOPLINKTHETA,TOPLINKHEIGHT,WHEELRADIUS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Jun-2020 04:02:18

t2 = cos(boardTheta);
t3 = sin(boardTheta);
t4 = boardTheta+bottomLinkTheta;
t6 = boardHeight./2.0;
FK_pivot = [boardX-(boardLength.*t3)./2.0;boardY+t6+wheelRadius+(boardLength.*t2)./2.0];
if nargout > 1
    t5 = t4+topLinkTheta;
    FK_tip = [boardX-(boardHeight.*t3)./2.0-bottomLinkHeight.*sin(t4)-topLinkHeight.*sin(t5);boardY+t6+wheelRadius+t2.*t6+bottomLinkHeight.*cos(t4)+topLinkHeight.*cos(t5)];
end
