%% constraints_ramp.m
%
% Description:
%   Wrapper function for autogen_constraints_ramp.m
%   Computes the constraint forces of the robot in the ramp stage.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   C_all = values of two constraint equations

function [C_all] = constraints_ramp(x,params)

[r_l,r_r] = wheel_coordinates(x,params);

[p_l,~,n_l] = track(x(11),params);
[p_r,~,n_r] = track(x(12),params);

pLeftX = p_l(1);
pLeftY = p_l(2);
pRightX = p_r(1);
pRightY = p_r(2);
normLeftX = n_l(1);
normLeftY = n_l(2);
normRightX = n_r(1);
normRightY = n_r(2);

% autogen inputs:
% boardX,boardY,boardTheta,boardHeight,boardLength,
% normLeftX,normLeftY,normRightX,normRightY,
% pLeftX,pLeftY,pRightX,pRightY,wheelRadius

if x(1) - params.boardLength/2 <= -2 
    
C_all = autogen_constraints_ramp_lip(x(2), x(3), params.boardHeight,...
                                 params.boardLength, params.wheelRadius);

else
    
C_all = autogen_constraints_ramp(x(1), x(2), x(3), params.boardHeight,...
                            params.boardLength, normLeftX, normLeftY,...
                            normRightX, normRightY, pLeftX, pLeftY,...
                            pRightX, pRightY, params.wheelRadius);
                        
end

end

