%% totalEnergy.m
%
% Description:
%   Wrapper function for autogen_total_energy.m
%   Computes the total energy of the robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot; s];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   TE = value of total energy in J

function TE = totalEnergy(x,params)


% autogen inputs:
% boardI,boardY,boardDX,boardDY,boardMass,
% boardTheta,boardDTheta,boardHeight,bottomLinkI,bottomLinkRCoM,
% bottomLinkMass,bottomLinkTheta,bottomLinkDTheta,bottomLinkHeight,g,topLinkI,
% topLinkRCoM,topLinkMass,topLinkTheta,topLinkDTheta,wheelRadius

TE = autogen_total_energy(params.boardI, x(2), x(6), x(7), params.boardMass,...
                          x(3), x(8), params.boardHeight, params.bottomLinkI,...
                          params.bottomLinkYCoM, params.bottomLinkMass, x(4),...
                          x(9), params.bottomLinkHeight, params.g, params.topLinkI,...
                          params.topLinkYCoM, params.topLinkMass, x(5), x(10),...
                          params.wheelRadius);
end