%% track.m
%
% Description:
%   function that computes the 2x1 vectors position, tangent and normal for
%   a semicircular track
%
% Inputs:
%   s: the pathlength along the track, measured from the bottom
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   p: a 2x1 position vector
%   t: a 2x1 tangent vector pointing in the direction of increasing
%   pathlength
%   n: a 2x1 normal vector pointing into the track surface

function [p,t,n] = track(s,params)

r = params.trackRadius;

p = [r*sin(s/r); r*(1 - cos(s/r))];

t = [cos(s/r); sin(s/r)];

n = [sin(s/r); -cos(s/r)];

end


