%% upright_input_matrix.m
%
% Description:
%   Wrapper function for autogen_upright_input_matrix.m
%   Computes the input matrix for linearized cart-pendulum dynamics in the
%   neighborhood of the upright (unstable) equilibrium.
%
% Inputs:
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs
%   B: 4x1 input matrix

function B = upright_input_matrix(params)
% 
% boardI,boardMass,bottomLinkI,bottomLinkRCoM,
% bottomLinkMass,bottomLinkHeight,topLinkI,
% topLinkRCoM,topLinkMass

    B = autogen_upright_input_matrix(params.boardI,...
                                     params.boardMass,...
                                     params.bottomLinkI,...
                                     params.bottomLinkYCoM,...
                                     params.bottomLinkMass,...
                                     params.bottomLinkHeight,...
                                     params.topLinkI,...
                                     params.topLinkYCoM,...
                                     params.topLinkMass);
end